### ISSUE TITLE
Having problem using ODAS Studio

### ISSUE THREAD

**Issue by SaeedSaedi70** [introlab/odas_web#15]
Hey there,
I downloaded ODAS Studio for windows. When I run ODAS Studio and set ODAS Control part, consisting of ODAS Core and ODAS Configure, then when I press "Launch ODAS" button, an error occurs. I have attached a photo that shows the error. Please help me with this issue. 
Thank you .
![error](https://user-images.githubusercontent.com/29304412/42376366-26a09676-8134-11e8-8f2d-23fbff09f953.JPG)

**Comment by GodCed** [comment]
Hi, this message means that ODAS Studio is not able to start the ODAS process.
I would suggest you try to launch it in command line rather than trough the Studio to see if you can get more information.

Also, you seem to be running Windows. Are you trying to run ODAS on windows? As far as I know, the ODAS core can only be run on Linux.

**Comment by SaeedSaedi70** [comment]
That's right.
Could you tell me please how to run that in command line, I mean, what exactly should I write there?

I'm running on Windows. But I have already launched it on Linux, I've got the ".bin" output there, then I added ".bin" file to my ODAS Core in Windows. It isn't working. Any suggestions on windows?

Thanks.

**Comment by GodCed** [comment]
Per the [ODAS Wiki](https://github.com/introlab/odas/wiki#running):
`./odaslive -c myConfigFile.cfg`

You can't run the ODAS Core in Windows. It uses libraries such as Alsa which are only on Linux.
Furthermore, you cannot build a binary file for Linux then copy it to Windows and run it. It must be built for the correct platform.
