### ISSUE TITLE
no reply on odas issues

### ISSUE THREAD

**Issue by kimchi88** [introlab/odas_web#19]
Dear developers,
I at texting here again because after your suggestion to post my latest issue on the Odas repository, I see that since 20 days there is nobody who is replying. This is happening not only for my post but also for others.
Is anyone of your team still following Odas's issues?

Thanks for your help

**Comment by FrancoisGrondin** [comment]
Hi Kimchi,

We are doing our very best to reply, but are a small team and sometimes have a hard time to give you fast feedback. Odas in its actual form is a beta version, and we hope that the first release will be stable and well documented, so that users can find direct answers from the documentation. Sometimes, assigning the issue to a specific developer can also help speed this up as many issues are configuration/application issues and are answered by other Odas users who did experiment with a similar hardware, and Odas developers are often out of the loop.
